In [1]:
import pandas as pd
import numpy as np

In [3]:
# Read in rock.csv as a data frame
rock = pd.read_csv('CSV/rock.csv')
rock

,Song Clean,ARTIST CLEAN,Release Year,COMBINED,First?,Year?,PlayCount,F*G
0,Caught Up in You,.38 Special,1982,Caught Up in You by .38 Special,1,1,82,82
1,Fantasy Girl,.38 Special,NaN,Fantasy Girl by .38 Special,1,0,3,0
2,Hold On Loosely,.38 Special,1981,Hold On Loosely by .38 Special,1,1,85,85
3,Rockin' Into the Night,.38 Special,1980,Rockin' Into the Night by .38 Special,1,1,18,18
4,Art For Arts Sake,10cc,1975,Art For Arts Sake by 10cc,1,1,1,1
5,Kryptonite,3 Doors Down,2000,Kryptonite by 3 Doors Down,1,1,13,13
6,Loser,3 Doors Down,2000,Loser by 3 Doors Down,1,1,1,1
7,When I'm Gone,3 Doors Down,2002,When I'm Gone by 3 Doors Down,1,1,6,6
8,What's Up?,4 Non Blondes,1992,What's Up? by 4 Non Blondes,1,1,3,3
9,Take On Me,a-ha,1985,Take On Me by a-ha,1,1,1,1
10,"Baby, Please Don't Go",AC/DC,NaN,"Baby, Please Don't Go by AC/DC",1,0,1,0
11,Back In Black,AC/DC,1980,Back In Black by AC/DC,1,1,97,97
12,Big Gun,AC/DC,1993,Big Gun by AC/DC,1,1,6,6
13,CAN'T STOP ROCK'N'ROLL,AC/DC,NaN,CAN'T STOP ROCK'N'ROLL by AC/DC,1,0,5,0
14,Dirty Deeds Done Dirt Cheap,AC/DC,1976,Dirty Deeds Done Dirt Cheap by AC/DC,1,1,85,85
15,For Those About To Rock,AC/DC,1981,For Those About To Rock by AC/DC,1,1,46,46
16,Girls Got Rhythm,AC/DC,NaN,Girls Got Rhythm by AC/DC,1,0,24,0
17,Hard As A Rock,AC/DC,1995,Hard As A Rock by AC/DC,1,1,1,1
18,Have a Drink On Me,AC/DC,1980,Have a Drink On Me by AC/DC,1,1,39,39
19,Hells Bells,AC/DC,1980,Hells Bells by AC/DC,1,1,74,74
20,Highway To Hell,AC/DC,1979,Highway To Hell by AC/DC,1,1,92,92
21,It's A Long Way To The Top,AC/DC,1975,It's A Long Way To The Top by AC/DC,1,1,39,39
22,Jailbreak,AC/DC,1984,Jailbreak by AC/DC,1,1,1,1
23,Let There Be Rock,AC/DC,1977,Let There Be Rock by AC/DC,1,1,3,3
24,Let's Get It Up,AC/DC,NaN,Let's Get It Up by AC/DC,1,0,4,0
25,Live Wire,AC/DC,NaN,Live Wire by AC/DC,1,0,2,0
26,Moneytalks,AC/DC,NaN,Moneytalks by AC/DC,1,0,20,0
27,Night Prowler,AC/DC,1979,Night Prowler by AC/DC,1,1,1,1
28,Rock and Roll Ain't Noise Pollution,AC/DC,1980,Rock and Roll Ain't Noise Pollution by AC/DC,1,1,21,21
29,Shoot To Thrill,AC/DC,NaN,Shoot To Thrill by AC/DC,1,0,45,0
...,...,...,...,...,...,...,...,...
2200,Owner of a Lonely Heart,Yes,1983,Owner of a Lonely Heart by Yes,1,1,81,81
2201,Roundabout,Yes,1971,Roundabout by Yes,1,1,44,44
2202,Starship Trooper,Yes,1971,Starship Trooper by Yes,1,1,1,1
2203,Wonderous Stories,Yes,NaN,Wonderous Stories by Yes,1,0,5,0
2204,Yours Is No Disgrace,Yes,1971,Yours Is No Disgrace by Yes,1,1,1,1
2205,Tell Me What You Want,Zebra,NaN,Tell Me What You Want by Zebra,1,0,2,0
2206,Who's Behind The Door,Zebra,NaN,Who's Behind The Door by Zebra,1,0,1,0
2207,Time of the Season,Zombies,1968,Time of the Season by Zombies,1,1,14,14
2208,A Fool for Your Stockings,ZZ Top,NaN,A Fool for Your Stockings by ZZ Top,1,0,1,0
2209,Arrested For Driving While Blind,ZZ Top,1976,Arrested For Driving While Blind by ZZ Top,1,1,1,1
2210,Beer Drinkers & Hell Raisers,ZZ Top,1973,Beer Drinkers & Hell Raisers by ZZ Top,1,1,8,8
2211,Cheap Sunglasses,ZZ Top,1980,Cheap Sunglasses by ZZ Top,1,1,34,34
2212,Gimme All Your Lovin,ZZ Top,1983,Gimme All Your Lovin by ZZ Top,1,1,86,86
2213,Got Me Under Pressure,ZZ Top,1983,Got Me Under Pressure by ZZ Top,1,1,29,29
2214,Heard It On the X,ZZ Top,1975,Heard It On the X by ZZ Top,1,1,2,2
2215,I Thank You,ZZ Top,NaN,I Thank You by ZZ Top,1,0,16,0
2216,"I'm Bad, I'm Nationwide",ZZ Top,NaN,"I'm Bad, I'm Nationwide by ZZ Top",1,0,10,0
2217,Jesus Just Left Chicago,ZZ Top,1973,Jesus Just Left Chicago by ZZ Top,1,1,6,6
2218,Just Got Paid,ZZ Top,NaN,Just Got Paid by ZZ Top,1,0,2,0
2219,La Grange,ZZ Top,1973,La Grange by ZZ Top,1,1,111,111
2220,Legs,ZZ Top,1983,Legs by ZZ Top,1,1,121,121
2221,My Head's In Mississippi,ZZ Top,NaN,My Head's In Mississippi by ZZ Top,1,0,1,0
2222,Party On The Patio,ZZ Top,NaN,Party On The Patio by ZZ Top,1,0,14,0
2223,Pearl Necklace,ZZ Top,1981,Pearl Necklace by ZZ Top,1,1,5,5
2224,Sharp Dressed Man,ZZ Top,1983,Sharp Dressed Man by ZZ Top,1,1,120,120
2225,She Loves My Automobile,ZZ Top,NaN,She Loves My Automobile by ZZ Top,1,0,1,0
2226,Tube Snake Boogie,ZZ Top,1981,Tube Snake Boogie by ZZ Top,1,1,32,32
2227,Tush,ZZ Top,1975,Tush by ZZ Top,1,1,109,109
2228,TV Dinners,ZZ Top,1983,TV Dinners by ZZ Top,1,1,1,1
2229,WAITIN' FOR THE BUS/JESUS JUST LEFT CHICAGO,ZZ Top,1973,WAITIN' FOR THE BUS/JESUS JUST LEFT CHICAGO by...,1,1,2,2

In [4]:
# The simplest pivot table must have a dataframe and an 
# index . Let’s use the ARTIST CLEAN as our index.
pd.pivot_table(rock, index='ARTIST CLEAN')

                                F*G  First?  PlayCount     Year?
ARTIST CLEAN
.38 Special               46.250000     1.0  47.000000  0.750000
10cc                       1.000000     1.0   1.000000  1.000000
3 Doors Down               6.666667     1.0   6.666667  1.000000
4 Non Blondes              3.000000     1.0   3.000000  1.000000
AC/DC                     26.275862     1.0  29.862069  0.689655
Ace                        1.000000     1.0   1.000000  1.000000
Adelitas Way               4.000000     1.0   4.000000  1.000000
Aerosmith                 23.645161     1.0  26.225806  0.806452
Alanis Morissette          3.500000     1.0   3.500000  1.000000
Alannah Myles              1.000000     1.0   1.000000  1.000000
Aldo Nova                  0.000000     1.0   4.000000  0.000000
Alice Cooper              14.200000     1.0  14.400000  0.800000
Alice In Chains            3.666667     1.0   3.666667  1.000000
Allman Brothers Band       6.538462     1.0   7.384615  0.769231
America                   15.333333     1.0  15.333333  1.000000
Animals II                 1.000000     1.0   1.000000  1.000000
Ann Wilson                 0.000000     1.0   2.000000  0.000000
April Wine                 0.000000     1.0   1.000000  0.000000
Argent                    11.000000     1.0  11.000000  1.000000
Arlo Guthrie               0.000000     1.0   1.000000  0.000000
Artful Dodger              0.000000     1.0   1.000000  0.000000
Asia                      20.000000     1.0  20.000000  1.000000
Atlanta Rhythm Section     0.500000     1.0   1.000000  0.500000
Audioslave                 1.000000     1.0   1.000000  1.000000
Autograph                 10.500000     1.0  11.000000  0.500000
Axe                        0.000000     1.0   1.000000  0.000000
Bachman-Turner Overdrive  30.250000     1.0  31.500000  0.750000
Bad Company               17.214286     1.0  40.500000  0.357143
Bad English                1.000000     1.0   1.000000  1.000000
Badfinger                  2.000000     1.0   2.000000  1.000000
...                             ...     ...        ...       ...
Trapeze                    0.000000     1.0   1.000000  0.000000
Triumph                    0.200000     1.0  17.600000  0.200000
Turtles                    1.000000     1.0   1.000000  1.000000
Twisted Sister            23.000000     1.0  23.000000  1.000000
U2                        23.368421     1.0  23.368421  1.000000
UB40                       2.000000     1.0   2.000000  1.000000
UFO                        0.500000     1.0  10.000000  0.500000
Uriah Heep                 1.000000     1.0   2.333333  0.666667
Van Halen                 23.977273     1.0  28.250000  0.613636
Van Morrison               7.700000     1.0   8.100000  0.600000
Violent Femmes             1.000000     1.0   1.000000  1.000000
Vixen                      0.000000     1.0   2.000000  0.000000
War                       21.750000     1.0  21.750000  1.000000
Warrant                    3.000000     1.0   3.500000  0.500000
Warren Zevon              27.500000     1.0  27.500000  1.000000
Weezer                     2.000000     1.0   2.000000  1.000000
Wet Willie                 0.000000     1.0   2.000000  0.000000
White Lion                 0.000000     1.0   1.000000  0.000000
Whitesnake                15.833333     1.0  19.166667  0.666667
Why Not                    0.000000     1.0   5.000000  0.000000
Wild Cherry                4.000000     1.0   4.000000  1.000000
Wildlife                   0.000000     1.0  13.500000  0.000000
Winger                     0.000000     1.0   1.333333  0.000000
Wishbone Ash               1.000000     1.0   1.000000  1.000000
Y&T                        0.000000     1.0   4.000000  0.000000
Yes                       23.200000     1.0  23.700000  0.900000
ZZ Top                    30.318182     1.0  32.363636  0.681818
Zebra                      0.000000     1.0   1.500000  0.000000
Zombies                   14.000000     1.0  14.000000  1.000000
a-ha                       1.000000     1.0   1.000000  1.000000

[475 rows x 4 columns]

In [5]:
# How about indexing on multiple values. Let's look at the 
# data by ARTIST CLEAN and Release Year next. 
pd.pivot_table(rock, index=['ARTIST CLEAN', 'Release Year'])

                                   F*G  First?  PlayCount  Year?
ARTIST CLEAN   Release Year
.38 Special    1980          18.000000     1.0  18.000000    1.0
               1981          85.000000     1.0  85.000000    1.0
               1982          82.000000     1.0  82.000000    1.0
10cc           1975           1.000000     1.0   1.000000    1.0
3 Doors Down   2000           7.000000     1.0   7.000000    1.0
               2002           6.000000     1.0   6.000000    1.0
4 Non Blondes  1992           3.000000     1.0   3.000000    1.0
AC/DC          1975          52.500000     1.0  52.500000    1.0
               1976          85.000000     1.0  85.000000    1.0
               1977           3.000000     1.0   3.000000    1.0
               1979          24.250000     1.0  24.250000    1.0
               1980          73.800000     1.0  73.800000    1.0
               1981          46.000000     1.0  46.000000    1.0
               1984           1.000000     1.0   1.000000    1.0
               1986          12.000000     1.0  12.000000    1.0
               1990          34.000000     1.0  34.000000    1.0
               1993           6.000000     1.0   6.000000    1.0
               1995           1.000000     1.0   1.000000    1.0
Ace            1974           1.000000     1.0   1.000000    1.0
Adelitas Way   2014           4.000000     1.0   4.000000    1.0
Aerosmith      1973          73.500000     1.0  73.500000    1.0
               1974          11.666667     1.0  11.666667    1.0
               1975          50.800000     1.0  50.800000    1.0
               1976          21.500000     1.0  21.500000    1.0
               1977           1.000000     1.0   1.000000    1.0
               1985           1.000000     1.0   1.000000    1.0
               1987          33.666667     1.0  33.666667    1.0
               1989          33.333333     1.0  33.333333    1.0
               1993          16.333333     1.0  16.333333    1.0
               1997           1.000000     1.0   1.000000    1.0
...                                ...     ...        ...    ...
Van Halen      1984          54.000000     1.0  54.000000    1.0
               1986          19.250000     1.0  19.250000    1.0
               1988          22.000000     1.0  22.000000    1.0
               1991          13.000000     1.0  13.000000    1.0
Van Morrison   1967          55.000000     1.0  55.000000    1.0
               1970           4.250000     1.0   4.250000    1.0
               1971           5.000000     1.0   5.000000    1.0
Violent Femmes 1982           1.000000     1.0   1.000000    1.0
War            1970           2.000000     1.0   2.000000    1.0
               1972           3.000000     1.0   3.000000    1.0
               1975          41.000000     1.0  41.000000    1.0
Warrant        1990           6.000000     1.0   6.000000    1.0
Warren Zevon   1978          27.500000     1.0  27.500000    1.0
Weezer         1994           2.000000     1.0   2.000000    1.0
Whitesnake     1980           3.000000     1.0   3.000000    1.0
               1984           1.000000     1.0   1.000000    1.0
               1987          45.500000     1.0  45.500000    1.0
Wild Cherry    1976           4.000000     1.0   4.000000    1.0
Wishbone Ash   1980           1.000000     1.0   1.000000    1.0
Yes            1971          20.000000     1.0  20.000000    1.0
               1972          35.000000     1.0  35.000000    1.0
               1983          29.250000     1.0  29.250000    1.0
ZZ Top         1973          31.750000     1.0  31.750000    1.0
               1975          55.500000     1.0  55.500000    1.0
               1976           1.000000     1.0   1.000000    1.0
               1980          34.000000     1.0  34.000000    1.0
               1981          18.500000     1.0  18.500000    1.0
               1983          71.400000     1.0  71.400000    1.0
Zombies        1968          14.000000     1.0  14.000000    1.0
a-ha           1985           1.000000     1.0   1.000000    1.0

[910 rows x 4 columns]

In [6]:
# What we really want to take a look at next is PlayCount. So, 
# the F*G, First?, and Year? columns aren’t useful. Let’s 
# remove them and explicitly define the 'PlayCount' column by 
# using the values field.
pd.pivot_table(rock, index=['ARTIST CLEAN', 'Release Year'], values='PlayCount')

ARTIST CLEAN    Release Year
.38 Special     1980            18.000000
                1981            85.000000
                1982            82.000000
10cc            1975             1.000000
3 Doors Down    2000             7.000000
                2002             6.000000
4 Non Blondes   1992             3.000000
AC/DC           1975            52.500000
                1976            85.000000
                1977             3.000000
                1979            24.250000
                1980            73.800000
                1981            46.000000
                1984             1.000000
                1986            12.000000
                1990            34.000000
                1993             6.000000
                1995             1.000000
Ace             1974             1.000000
Adelitas Way    2014             4.000000
Aerosmith       1973            73.500000
                1974            11.666667
                1975            50.800000
                1976            21.500000
                1977             1.000000
                1985             1.000000
                1987            33.666667
                1989            33.333333
                1993            16.333333
                1997             1.000000
                                  ...
Van Halen       1984            54.000000
                1986            19.250000
                1988            22.000000
                1991            13.000000
Van Morrison    1967            55.000000
                1970             4.250000
                1971             5.000000
Violent Femmes  1982             1.000000
War             1970             2.000000
                1972             3.000000
                1975            41.000000
Warrant         1990             6.000000
Warren Zevon    1978            27.500000
Weezer          1994             2.000000
Whitesnake      1980             3.000000
                1984             1.000000
                1987            45.500000
Wild Cherry     1976             4.000000
Wishbone Ash    1980             1.000000
Yes             1971            20.000000
                1972            35.000000
                1983            29.250000
ZZ Top          1973            31.750000
                1975            55.500000
                1976             1.000000
                1980            34.000000
                1981            18.500000
                1983            71.400000
Zombies         1968            14.000000
a-ha            1985             1.000000
Name: PlayCount, dtype: float64

In [12]:
# The 'PlayCount' column automatically averages the data.  
# We can do a count or a sum by using aggfunc and np.sum.
pd.pivot_table(rock, index=['ARTIST CLEAN', 'Release Year'], values='PlayCount', aggfunc=sum)

ARTIST CLEAN    Release Year
.38 Special     1980             18
                1981             85
                1982             82
10cc            1975              1
3 Doors Down    2000             14
                2002              6
4 Non Blondes   1992              3
AC/DC           1975            105
                1976             85
                1977              6
                1979             97
                1980            369
                1981             46
                1984              1
                1986             12
                1990             34
                1993              6
                1995              1
Ace             1974              1
Adelitas Way    2014              4
Aerosmith       1973            147
                1974             35
                1975            254
                1976             43
                1977              1
                1985              1
                1987            101
                1989            100
                1993             49
                1997              1
                               ...
Van Halen       1984            216
                1986             77
                1988             22
                1991             26
Van Morrison    1967             55
                1970             17
                1971              5
Violent Femmes  1982              1
War             1970              2
                1972              3
                1975             82
Warrant         1990              6
Warren Zevon    1978             55
Weezer          1994              2
Whitesnake      1980              3
                1984              1
                1987             91
Wild Cherry     1976              4
Wishbone Ash    1980              1
Yes             1971             80
                1972             35
                1983            117
ZZ Top          1973            127
                1975            111
                1976              1
                1980             34
                1981             37
                1983            357
Zombies         1968             14
a-ha            1985              1
Name: PlayCount, dtype: int64