# Data Workflow Lab 1

Clean and summarize Project 3 data.

### Learning Objectives

* Practice text cleaning techniques
* Practice datatype conversion
* Practice filling in missing values with either 0 or the average in the column
* Practice categorical data techniques
* Transform data into usable quantities

In [1]:
% matplotlib inline
import datetime
import numpy as np
import pandas as pd

**Load the data**

In [2]:
df = pd.read_csv("CSV/Iowa_Liquor_sales_sample_10pct.csv")
print df.columns
df.head()

Index([u'Date', u'Store Number', u'City', u'Zip Code', u'County Number',
       u'County', u'Category', u'Category Name', u'Vendor Number',
       u'Item Number', u'Item Description', u'Bottle Volume (ml)',
       u'State Bottle Cost', u'State Bottle Retail', u'Bottles Sold',
       u'Sale (Dollars)', u'Volume Sold (Liters)', u'Volume Sold (Gallons)'],
      dtype='object')

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
0,11/04/2015,3717,SUMNER,50674,9.0,Bremer,1051100.0,APRICOT BRANDIES,55,54436,Mr. Boston Apricot Brandy,750,$4.50,$6.75,12,$81.00,9.0,2.38
1,03/02/2016,2614,DAVENPORT,52807,82.0,Scott,1011100.0,BLENDED WHISKIES,395,27605,Tin Cup,750,$13.75,$20.63,2,$41.26,1.5,0.40
2,02/11/2016,2106,CEDAR FALLS,50613,7.0,Black Hawk,1011200.0,STRAIGHT BOURBON WHISKIES,65,19067,Jim Beam,1000,$12.59,$18.89,24,$453.36,24.0,6.34
3,02/03/2016,2501,AMES,50010,85.0,Story,1071100.0,AMERICAN COCKTAILS,395,59154,1800 Ultimate Margarita,1750,$9.50,$14.25,6,$85.50,10.5,2.77
4,08/18/2015,3654,BELMOND,50421,99.0,Wright,1031080.0,VODKA 80 PROOF,297,35918,Five O'clock Vodka,1750,$7.20,$10.80,12,$129.60,21.0,5.55

## Clean the data

Let's practice our data cleaning skills on the Project 3 dataset. If you don't remember how to do any of these tasks, look back at your work from the previous weeks or search the internet. There are many blog articles and Stack Overflow posts that cover these topics.

You'll want to complete at least the following tasks:
* Remove redundant columns
* Remove "$" prices from characters and convert values to floats.
* Convert dates to pandas datetime objects
* Convert category floats to integers
* Drop or fill in bad values

**Remove redundant columns**

In [3]:
df.drop(['County', 'Category Name', 'Vendor Number', 'Item Description', 'Volume Sold (Gallons)'], axis=1, inplace=True)

In [4]:
df.head()

,Date,Store Number,City,Zip Code,County Number,Category,Item Number,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters)
0,11/04/2015,3717,SUMNER,50674,9.0,1051100.0,54436,750,$4.50,$6.75,12,$81.00,9.0
1,03/02/2016,2614,DAVENPORT,52807,82.0,1011100.0,27605,750,$13.75,$20.63,2,$41.26,1.5
2,02/11/2016,2106,CEDAR FALLS,50613,7.0,1011200.0,19067,1000,$12.59,$18.89,24,$453.36,24.0
3,02/03/2016,2501,AMES,50010,85.0,1071100.0,59154,1750,$9.50,$14.25,6,$85.50,10.5
4,08/18/2015,3654,BELMOND,50421,99.0,1031080.0,35918,1750,$7.20,$10.80,12,$129.60,21.0

**Remove $ from certain columns**

In [5]:
df['State Bottle Cost'] = df['State Bottle Cost'].str.extract('([^$][0-9.]*)').astype(float)
df['State Bottle Retail'] = df['State Bottle Retail'].str.extract('([^$][0-9.]*)').astype(float)
df['Sale (Dollars)'] = df['Sale (Dollars)'].str.extract('([^$][0-9.]*)').astype(float)
df.head()

/home/useraj/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:2: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  from ipykernel import kernelapp as app
/home/useraj/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:3: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  app.launch_new_instance()
/home/useraj/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:4: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)

,Date,Store Number,City,Zip Code,County Number,Category,Item Number,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters)
0,11/04/2015,3717,SUMNER,50674,9.0,1051100.0,54436,750,4.50,6.75,12,81.00,9.0
1,03/02/2016,2614,DAVENPORT,52807,82.0,1011100.0,27605,750,13.75,20.63,2,41.26,1.5
2,02/11/2016,2106,CEDAR FALLS,50613,7.0,1011200.0,19067,1000,12.59,18.89,24,453.36,24.0
3,02/03/2016,2501,AMES,50010,85.0,1071100.0,59154,1750,9.50,14.25,6,85.50,10.5
4,08/18/2015,3654,BELMOND,50421,99.0,1031080.0,35918,1750,7.20,10.80,12,129.60,21.0

**Convert dates**

In [6]:
df.Date = pd.to_datetime(df["Date"])
df.head()

,Date,Store Number,City,Zip Code,County Number,Category,Item Number,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters)
0,2015-11-04,3717,SUMNER,50674,9.0,1051100.0,54436,750,4.50,6.75,12,81.00,9.0
1,2016-03-02,2614,DAVENPORT,52807,82.0,1011100.0,27605,750,13.75,20.63,2,41.26,1.5
2,2016-02-11,2106,CEDAR FALLS,50613,7.0,1011200.0,19067,1000,12.59,18.89,24,453.36,24.0
3,2016-02-03,2501,AMES,50010,85.0,1071100.0,59154,1750,9.50,14.25,6,85.50,10.5
4,2015-08-18,3654,BELMOND,50421,99.0,1031080.0,35918,1750,7.20,10.80,12,129.60,21.0

**Drop or replace bad values and convert to integers**

In [7]:
df.dropna(inplace=True)
df['County Number'] = df['County Number'].astype(int)
df['Category'] = df['Category'].astype(int)

**One zip code was entered as part of a number, so I looked up correct zip code and replaced it**

In [8]:
df = df.replace('712-2', '51529')
df['Zip Code'] = df['Zip Code'].astype(int)
df.dtypes

Date                    datetime64[ns]
Store Number                     int64
City                            object
Zip Code                         int64
County Number                    int64
Category                         int64
Item Number                      int64
Bottle Volume (ml)               int64
State Bottle Cost              float64
State Bottle Retail            float64
Bottles Sold                     int64
Sale (Dollars)                 float64
Volume Sold (Liters)           float64
dtype: object

## Filter the Data

Some stores may have opened or closed in 2015. These data points will heavily skew our models, so we need to filter them out or find a way to deal with them.

You'll need to provide a summary in your project report about these data points. You may also consider using the monthly sales in your model and including other information (number of months or days each store is open) in your data to handle these unusual cases.

Let's record the first and last sales dates for each store. We'll save this information for later when we fit our models.

**Added 'First Date' and 'Last Date' columns**

In [9]:
dates = pd.pivot_table(df, index="Store Number", values="Date", aggfunc=(min, max))
df = df.merge(dates, left_on='Store Number', right_index=True)
df

,Date,Store Number,City,Zip Code,County Number,Category,Item Number,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),min,max
0,2015-11-04,3717,SUMNER,50674,9,1051100,54436,750,4.50,6.75,12,81.00,9.00,2015-01-07,2016-03-30
15,2015-06-10,3717,SUMNER,50674,9,1051100,54436,750,4.50,6.75,4,27.00,3.00,2015-01-07,2016-03-30
3292,2015-01-21,3717,SUMNER,50674,9,1081900,75211,750,10.00,15.00,2,30.00,1.50,2015-01-07,2016-03-30
3399,2015-11-11,3717,SUMNER,50674,9,1012100,11777,1000,6.63,9.95,2,19.90,2.00,2015-01-07,2016-03-30
3691,2015-01-07,3717,SUMNER,50674,9,1011200,19476,750,16.79,25.19,1,25.19,0.75,2015-01-07,2016-03-30
3778,2015-02-18,3717,SUMNER,50674,9,1012300,15621,600,11.88,17.82,1,17.82,0.60,2015-01-07,2016-03-30
3804,2016-03-23,3717,SUMNER,50674,9,1011100,25607,1000,8.00,12.00,2,24.00,2.00,2015-01-07,2016-03-30
4073,2015-08-19,3717,SUMNER,50674,9,1062300,44520,750,6.83,10.25,1,10.25,0.75,2015-01-07,2016-03-30
5611,2015-12-09,3717,SUMNER,50674,9,1012100,11296,750,15.00,22.50,2,45.00,1.50,2015-01-07,2016-03-30
6700,2016-02-10,3717,SUMNER,50674,9,1081030,67527,1000,15.49,23.24,1,23.24,1.00,2015-01-07,2016-03-30
8237,2015-02-04,3717,SUMNER,50674,9,1081200,80482,500,7.42,11.13,1,11.13,0.50,2015-01-07,2016-03-30
9287,2016-03-02,3717,SUMNER,50674,9,1012200,5326,750,20.99,31.49,1,31.49,0.75,2015-01-07,2016-03-30
9868,2016-01-13,3717,SUMNER,50674,9,1062310,77318,1750,10.00,15.00,6,90.00,10.50,2015-01-07,2016-03-30
11781,2016-03-09,3717,SUMNER,50674,9,1051100,54436,750,4.50,6.75,4,27.00,3.00,2015-01-07,2016-03-30
12061,2015-12-22,3717,SUMNER,50674,9,1031200,41694,1000,7.50,11.25,5,56.25,5.00,2015-01-07,2016-03-30
15084,2016-01-20,3717,SUMNER,50674,9,1081600,64868,1750,15.33,23.00,1,23.00,1.75,2015-01-07,2016-03-30
15133,2015-04-29,3717,SUMNER,50674,9,1012100,11297,1000,18.50,27.75,1,27.75,1.00,2015-01-07,2016-03-30
18837,2016-02-10,3717,SUMNER,50674,9,1012100,11588,1750,12.99,19.49,2,38.98,3.50,2015-01-07,2016-03-30
19994,2015-10-28,3717,SUMNER,50674,9,1081370,82866,750,6.30,9.45,2,18.90,1.50,2015-01-07,2016-03-30
20547,2015-04-08,3717,SUMNER,50674,9,1011200,21598,1750,9.24,13.86,1,13.86,1.75,2015-01-07,2016-03-30
20973,2015-01-14,3717,SUMNER,50674,9,1081390,69636,750,8.67,13.01,2,26.02,1.50,2015-01-07,2016-03-30
21315,2015-01-07,3717,SUMNER,50674,9,1062310,43285,750,9.00,13.50,2,27.00,1.50,2015-01-07,2016-03-30
23150,2015-11-23,3717,SUMNER,50674,9,1031200,41694,1000,7.50,11.25,3,33.75,3.00,2015-01-07,2016-03-30
23345,2016-03-16,3717,SUMNER,50674,9,1081390,69637,1000,11.00,16.50,2,33.00,2.00,2015-01-07,2016-03-30
23636,2015-06-10,3717,SUMNER,50674,9,1031200,77842,750,8.25,12.38,2,24.76,1.50,2015-01-07,2016-03-30
23682,2015-08-05,3717,SUMNER,50674,9,1031080,37997,1000,9.25,13.88,3,41.64,3.00,2015-01-07,2016-03-30
26285,2015-10-28,3717,SUMNER,50674,9,1062310,1799,1750,18.00,27.00,3,81.00,5.25,2015-01-07,2016-03-30
26316,2016-03-16,3717,SUMNER,50674,9,1012100,10550,750,6.75,10.13,2,20.26,1.50,2015-01-07,2016-03-30
27970,2016-01-27,3717,SUMNER,50674,9,1051100,54436,750,4.13,6.38,3,19.14,2.25,2015-01-07,2016-03-30
28317,2015-11-04,3717,SUMNER,50674,9,1051110,55066,750,4.50,6.75,2,13.50,1.50,2015-01-07,2016-03-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228586,2015-03-19,3826,OSCEOLA,50213,20,1031080,35318,1750,6.92,10.38,12,124.56,21.00,2015-03-19,2015-12-10
89685,2016-02-23,4985,MERRILL,51038,75,1062310,43336,750,9.00,13.50,12,162.00,9.00,2015-04-21,2016-03-15
120376,2015-12-01,4985,MERRILL,51038,75,1031080,36904,375,1.80,2.70,6,16.20,2.25,2015-04-21,2016-03-15
150943,2015-04-21,4985,MERRILL,51038,75,1031080,35416,750,4.84,7.26,12,87.12,9.00,2015-04-21,2016-03-15
170175,2016-01-05,4985,MERRILL,51038,75,1062200,43126,750,8.26,12.39,6,74.34,4.50,2015-04-21,2016-03-15
181379,2015-12-01,4985,MERRILL,51038,75,1011300,26820,375,7.00,10.50,12,126.00,4.50,2015-04-21,2016-03-15
186311,2015-04-21,4985,MERRILL,51038,75,1062310,43024,375,2.74,4.11,24,98.64,9.00,2015-04-21,2016-03-15
219111,2016-02-23,4985,MERRILL,51038,75,1012100,11788,1750,9.70,14.93,3,44.79,5.25,2015-04-21,2016-03-15
233741,2016-03-15,4985,MERRILL,51038,75,1012100,11788,1750,10.45,15.68,12,188.16,21.00,2015-04-21,2016-03-15
246538,2015-12-01,4985,MERRILL,51038,75,1011100,25606,750,7.00,10.50,4,42.00,3.00,2015-04-21,2016-03-15
249857,2015-11-10,4985,MERRILL,51038,75,1062310,1799,1750,18.00,27.00,6,162.00,10.50,2015-04-21,2016-03-15
89810,2015-06-24,4737,STORM LAKE,50588,11,1031080,36308,1750,7.17,10.76,12,129.12,21.00,2015-06-24,2016-03-30
173646,2015-06-24,4737,STORM LAKE,50588,11,1031080,37996,750,8.25,12.38,12,148.56,9.00,2015-06-24,2016-03-30
180822,2015-11-18,4737,STORM LAKE,50588,11,1081030,67526,750,11.99,17.99,12,215.88,9.00,2015-06-24,2016-03-30
232175,2016-03-30,4737,STORM LAKE,50588,11,1062200,43126,750,8.26,12.39,12,148.68,9.00,2015-06-24,2016-03-30
98148,2015-01-15,4776,CARROLL,51401,14,1012100,11788,1750,10.45,15.68,12,188.16,21.00,2015-01-15,2015-03-05
103940,2015-03-05,4776,CARROLL,51401,14,1012100,11786,750,5.23,7.85,24,188.40,18.00,2015-01-15,2015-03-05
102645,2015-09-15,4338,MELBOURNE,50162,64,1012100,11788,1750,10.45,15.68,6,94.08,10.50,2015-03-31,2016-02-16
122448,2015-03-31,4338,MELBOURNE,50162,64,1012100,10549,600,7.12,10.68,20,213.60,12.00,2015-03-31,2016-02-16
129089,2015-03-31,4338,MELBOURNE,50162,64,1012100,11296,750,15.00,22.50,12,270.00,9.00,2015-03-31,2016-02-16
137888,2015-03-31,4338,MELBOURNE,50162,64,1012100,15248,1750,9.18,13.77,18,247.86,31.50,2015-03-31,2016-02-16
137899,2016-02-16,4338,MELBOURNE,50162,64,1012100,11786,750,5.23,7.85,12,94.20,9.00,2015-03-31,2016-02-16
204879,2015-05-19,4338,MELBOURNE,50162,64,1031080,36308,1750,7.17,10.76,6,64.56,10.50,2015-03-31,2016-02-16
107866,2016-03-08,9023,Carroll,51401,14,1011200,26996,750,17.59,26.39,24,633.36,18.00,2016-03-08,2016-03-08
139261,2015-10-27,9018,Dubuque,52001,31,1062310,46686,750,14.30,21.45,300,6435.00,225.00,2015-10-27,2015-10-27
182575,2015-12-01,5201,DUBUQUE,52001,31,1062200,43124,375,4.50,6.75,6,40.50,2.25,2015-12-01,2015-12-01
187731,2015-12-01,5201,DUBUQUE,52001,31,1052010,48105,375,9.99,14.99,12,179.88,4.50,2015-12-01,2015-12-01
247828,2015-12-01,5201,DUBUQUE,52001,31,1032080,34197,375,9.25,13.88,5,69.40,1.88,2015-12-01,2015-12-01
213289,2015-09-16,4778,STORM LAKE,50588,11,1701100,734,850,11.49,17.24,12,206.88,10.20,2015-09-16,2015-09-16
237259,2015-09-16,4778,STORM LAKE,50588,11,1022100,89199,375,5.50,8.25,12,99.00,4.50,2015-09-16,2015-09-16

In [10]:
df['First Date'] = df['min']
df['Last Date'] = df['max']

In [11]:
df.drop('min', axis=1, inplace=True)
df.drop('max', axis=1, inplace=True)
df

,Date,Store Number,City,Zip Code,County Number,Category,Item Number,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),First Date,Last Date
0,2015-11-04,3717,SUMNER,50674,9,1051100,54436,750,4.50,6.75,12,81.00,9.00,2015-01-07,2016-03-30
15,2015-06-10,3717,SUMNER,50674,9,1051100,54436,750,4.50,6.75,4,27.00,3.00,2015-01-07,2016-03-30
3292,2015-01-21,3717,SUMNER,50674,9,1081900,75211,750,10.00,15.00,2,30.00,1.50,2015-01-07,2016-03-30
3399,2015-11-11,3717,SUMNER,50674,9,1012100,11777,1000,6.63,9.95,2,19.90,2.00,2015-01-07,2016-03-30
3691,2015-01-07,3717,SUMNER,50674,9,1011200,19476,750,16.79,25.19,1,25.19,0.75,2015-01-07,2016-03-30
3778,2015-02-18,3717,SUMNER,50674,9,1012300,15621,600,11.88,17.82,1,17.82,0.60,2015-01-07,2016-03-30
3804,2016-03-23,3717,SUMNER,50674,9,1011100,25607,1000,8.00,12.00,2,24.00,2.00,2015-01-07,2016-03-30
4073,2015-08-19,3717,SUMNER,50674,9,1062300,44520,750,6.83,10.25,1,10.25,0.75,2015-01-07,2016-03-30
5611,2015-12-09,3717,SUMNER,50674,9,1012100,11296,750,15.00,22.50,2,45.00,1.50,2015-01-07,2016-03-30
6700,2016-02-10,3717,SUMNER,50674,9,1081030,67527,1000,15.49,23.24,1,23.24,1.00,2015-01-07,2016-03-30
8237,2015-02-04,3717,SUMNER,50674,9,1081200,80482,500,7.42,11.13,1,11.13,0.50,2015-01-07,2016-03-30
9287,2016-03-02,3717,SUMNER,50674,9,1012200,5326,750,20.99,31.49,1,31.49,0.75,2015-01-07,2016-03-30
9868,2016-01-13,3717,SUMNER,50674,9,1062310,77318,1750,10.00,15.00,6,90.00,10.50,2015-01-07,2016-03-30
11781,2016-03-09,3717,SUMNER,50674,9,1051100,54436,750,4.50,6.75,4,27.00,3.00,2015-01-07,2016-03-30
12061,2015-12-22,3717,SUMNER,50674,9,1031200,41694,1000,7.50,11.25,5,56.25,5.00,2015-01-07,2016-03-30
15084,2016-01-20,3717,SUMNER,50674,9,1081600,64868,1750,15.33,23.00,1,23.00,1.75,2015-01-07,2016-03-30
15133,2015-04-29,3717,SUMNER,50674,9,1012100,11297,1000,18.50,27.75,1,27.75,1.00,2015-01-07,2016-03-30
18837,2016-02-10,3717,SUMNER,50674,9,1012100,11588,1750,12.99,19.49,2,38.98,3.50,2015-01-07,2016-03-30
19994,2015-10-28,3717,SUMNER,50674,9,1081370,82866,750,6.30,9.45,2,18.90,1.50,2015-01-07,2016-03-30
20547,2015-04-08,3717,SUMNER,50674,9,1011200,21598,1750,9.24,13.86,1,13.86,1.75,2015-01-07,2016-03-30
20973,2015-01-14,3717,SUMNER,50674,9,1081390,69636,750,8.67,13.01,2,26.02,1.50,2015-01-07,2016-03-30
21315,2015-01-07,3717,SUMNER,50674,9,1062310,43285,750,9.00,13.50,2,27.00,1.50,2015-01-07,2016-03-30
23150,2015-11-23,3717,SUMNER,50674,9,1031200,41694,1000,7.50,11.25,3,33.75,3.00,2015-01-07,2016-03-30
23345,2016-03-16,3717,SUMNER,50674,9,1081390,69637,1000,11.00,16.50,2,33.00,2.00,2015-01-07,2016-03-30
23636,2015-06-10,3717,SUMNER,50674,9,1031200,77842,750,8.25,12.38,2,24.76,1.50,2015-01-07,2016-03-30
23682,2015-08-05,3717,SUMNER,50674,9,1031080,37997,1000,9.25,13.88,3,41.64,3.00,2015-01-07,2016-03-30
26285,2015-10-28,3717,SUMNER,50674,9,1062310,1799,1750,18.00,27.00,3,81.00,5.25,2015-01-07,2016-03-30
26316,2016-03-16,3717,SUMNER,50674,9,1012100,10550,750,6.75,10.13,2,20.26,1.50,2015-01-07,2016-03-30
27970,2016-01-27,3717,SUMNER,50674,9,1051100,54436,750,4.13,6.38,3,19.14,2.25,2015-01-07,2016-03-30
28317,2015-11-04,3717,SUMNER,50674,9,1051110,55066,750,4.50,6.75,2,13.50,1.50,2015-01-07,2016-03-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228586,2015-03-19,3826,OSCEOLA,50213,20,1031080,35318,1750,6.92,10.38,12,124.56,21.00,2015-03-19,2015-12-10
89685,2016-02-23,4985,MERRILL,51038,75,1062310,43336,750,9.00,13.50,12,162.00,9.00,2015-04-21,2016-03-15
120376,2015-12-01,4985,MERRILL,51038,75,1031080,36904,375,1.80,2.70,6,16.20,2.25,2015-04-21,2016-03-15
150943,2015-04-21,4985,MERRILL,51038,75,1031080,35416,750,4.84,7.26,12,87.12,9.00,2015-04-21,2016-03-15
170175,2016-01-05,4985,MERRILL,51038,75,1062200,43126,750,8.26,12.39,6,74.34,4.50,2015-04-21,2016-03-15
181379,2015-12-01,4985,MERRILL,51038,75,1011300,26820,375,7.00,10.50,12,126.00,4.50,2015-04-21,2016-03-15
186311,2015-04-21,4985,MERRILL,51038,75,1062310,43024,375,2.74,4.11,24,98.64,9.00,2015-04-21,2016-03-15
219111,2016-02-23,4985,MERRILL,51038,75,1012100,11788,1750,9.70,14.93,3,44.79,5.25,2015-04-21,2016-03-15
233741,2016-03-15,4985,MERRILL,51038,75,1012100,11788,1750,10.45,15.68,12,188.16,21.00,2015-04-21,2016-03-15
246538,2015-12-01,4985,MERRILL,51038,75,1011100,25606,750,7.00,10.50,4,42.00,3.00,2015-04-21,2016-03-15
249857,2015-11-10,4985,MERRILL,51038,75,1062310,1799,1750,18.00,27.00,6,162.00,10.50,2015-04-21,2016-03-15
89810,2015-06-24,4737,STORM LAKE,50588,11,1031080,36308,1750,7.17,10.76,12,129.12,21.00,2015-06-24,2016-03-30
173646,2015-06-24,4737,STORM LAKE,50588,11,1031080,37996,750,8.25,12.38,12,148.56,9.00,2015-06-24,2016-03-30
180822,2015-11-18,4737,STORM LAKE,50588,11,1081030,67526,750,11.99,17.99,12,215.88,9.00,2015-06-24,2016-03-30
232175,2016-03-30,4737,STORM LAKE,50588,11,1062200,43126,750,8.26,12.39,12,148.68,9.00,2015-06-24,2016-03-30
98148,2015-01-15,4776,CARROLL,51401,14,1012100,11788,1750,10.45,15.68,12,188.16,21.00,2015-01-15,2015-03-05
103940,2015-03-05,4776,CARROLL,51401,14,1012100,11786,750,5.23,7.85,24,188.40,18.00,2015-01-15,2015-03-05
102645,2015-09-15,4338,MELBOURNE,50162,64,1012100,11788,1750,10.45,15.68,6,94.08,10.50,2015-03-31,2016-02-16
122448,2015-03-31,4338,MELBOURNE,50162,64,1012100,10549,600,7.12,10.68,20,213.60,12.00,2015-03-31,2016-02-16
129089,2015-03-31,4338,MELBOURNE,50162,64,1012100,11296,750,15.00,22.50,12,270.00,9.00,2015-03-31,2016-02-16
137888,2015-03-31,4338,MELBOURNE,50162,64,1012100,15248,1750,9.18,13.77,18,247.86,31.50,2015-03-31,2016-02-16
137899,2016-02-16,4338,MELBOURNE,50162,64,1012100,11786,750,5.23,7.85,12,94.20,9.00,2015-03-31,2016-02-16
204879,2015-05-19,4338,MELBOURNE,50162,64,1031080,36308,1750,7.17,10.76,6,64.56,10.50,2015-03-31,2016-02-16
107866,2016-03-08,9023,Carroll,51401,14,1011200,26996,750,17.59,26.39,24,633.36,18.00,2016-03-08,2016-03-08
139261,2015-10-27,9018,Dubuque,52001,31,1062310,46686,750,14.30,21.45,300,6435.00,225.00,2015-10-27,2015-10-27
182575,2015-12-01,5201,DUBUQUE,52001,31,1062200,43124,375,4.50,6.75,6,40.50,2.25,2015-12-01,2015-12-01
187731,2015-12-01,5201,DUBUQUE,52001,31,1052010,48105,375,9.99,14.99,12,179.88,4.50,2015-12-01,2015-12-01
247828,2015-12-01,5201,DUBUQUE,52001,31,1032080,34197,375,9.25,13.88,5,69.40,1.88,2015-12-01,2015-12-01
213289,2015-09-16,4778,STORM LAKE,50588,11,1701100,734,850,11.49,17.24,12,206.88,10.20,2015-09-16,2015-09-16
237259,2015-09-16,4778,STORM LAKE,50588,11,1022100,89199,375,5.50,8.25,12,99.00,4.50,2015-09-16,2015-09-16

**Made store_info dataframe with City, County Number, and Zip Code**

In [12]:
store_info = pd.pivot_table(df, index=['Store Number', 'City'], values=['Zip Code', "County Number"])
store_info.reset_index(inplace=True)
store_info.set_index('Store Number', inplace=True)
store_info

                         City  County Number  Zip Code
Store Number
2106              CEDAR FALLS              7     50613
2113                   GOWRIE             94     50543
2130                 WATERLOO              7     50703
2152                 ROCKWELL             17     50469
2178                   WAUKON              3     52172
2190               DES MOINES             77     50314
2191                   KEOKUK             56     52632
2200                 SAC CITY             81     50583
2205                 CLARINDA             73     51632
2228                WINTERSET             61     50273
2233              SPIRIT LAKE             30     51360
2238                  ALTOONA             77     50009
2248               DES MOINES             77     50312
2285                IOWA CITY             52     52240
2290               STORM LAKE             11     50588
2327                  CORNING              2     50841
2353                   CRESCO             45     52136
2367               SHENANDOAH             73     51601
2413                  DUBUQUE             31     52001
2445                  OAKLAND             78     51560
2448                INDIANOLA             91     50125
2459           GUTHRIE CENTER             39     50115
2460                  HAMPTON             35     50441
2465                  DUBUQUE             31     52003
2475                WEST BEND             55     50597
2478                  ALTOONA             77     50009
2487                  ANAMOSA             53     52205
2498                ARLINGTON             33     50606
2500                     AMES             85     50010
2501                     AMES             85     50010
...                       ...            ...       ...
5185               CORALVILLE             52     52241
5186               WEST UNION             33     52175
5187                     AMES             85     50010
5188               SIOUX CITY             97     51101
5189          WEST DES MOINES             77     50266
5190                  WALFORD             57     52351
5191           GUTHRIE CENTER             39     50115
5192                   ROBINS             57     52328
5193                LOHRVILLE             13     51453
5195           COUNCIL BLUFFS             78     51530
5196               CORALVILLE             52     52241
5198                DAVENPORT             82     52803
5199                  OELWEIN             33     50662
5201                  DUBUQUE             31     52001
5202             GILBERTVILLE              7     50634
5203              COON RAPIDS             14     50058
5204               BURLINGTON             29     52601
5205                  GLIDDEN             14     51443
5206            GRUNDY CENTER             38     50638
5207             CEDAR RAPIDS             57     52404
5211                 JOHNSTON             77     50131
5212               MASON CITY             17     50401
5213                 MONTROSE             56     52639
5215                LE CLAIRE             82     52753
9001                  SWISHER             52     52338
9002                 LECLAIRE             82     52753
9010                  NORWALK             91     50211
9013                  Cumming             91     50061
9018                  Dubuque             31     52001
9023                  Carroll             14     51401

[1379 rows x 3 columns]

## Compute New Columns and Tables

Since we're trying to predict sales and/or profits, we'll want to compute some intermediate data. There are a lot of ways to do thisand good use of pandas is crucial. For example, for each transaction we may want to know:
* margin, retail cost minus bottle cost
* price per bottle
* price per liter

We'll need to make a new dataframe that indexes quantities by store:
* sales per store for all of 2015
* sales per store for Q1 2015
* sales per store for Q1 2016
* total volumes sold
* mean transaction revenue, gross margin, price per bottle, price per liter, etc.
* average sales per day
* number of days open

Make sure to retain other variables that we'll want to use to build our models, such as zip code, county number, city, etc. We recommend that you spend some time thinking about the model you may want to fit and computing enough of the suggested quantities to give you a few options.

Bonus tasks:
* Restrict your attention to stores that were open for all of 2015 and Q1 2016. Stores that opened or closed in 2015 will introduce outliers into your data.
* For each transaction we have the item category. You may be able to determine the store type (primarily wine, liquor, all types of alcohol, etc.) by the most common transaction category for each store. This could be a useful categorical variable for modelling.

**Added 'Margin' and 'Price per Liter' column**

In [13]:
# Margin and Price per liter
df['Margin'] = (df['State Bottle Retail'] - df['State Bottle Cost'])*df['Bottles Sold']
df['Price per Liter'] = df['Sale (Dollars)'] / df['Volume Sold (Liters)']

**Filtered out stores that opened or closed during our timeframe**

In [14]:
df = df[(df['First Date'] < pd.Timestamp("2015-01-19")) & (df['Last Date'] > pd.Timestamp("2016-03-17"))]

**Sales by store for 2015**

In [20]:
# Created with pivot tables
sales2015 = pd.pivot_table(df[(df['Date'] >= pd.Timestamp("2015-01-01")) & (df['Date'] <= pd.Timestamp("2015-12-31"))], 
                           index='Store Number',
                           aggfunc={
                                    'Bottles Sold': sum,
                                    'State Bottle Retail': np.mean,
                                    'Volume Sold (Liters)': {'Total Volume Sold': sum, 'Average Volume Sold': np.mean},
                                    'Margin': np.mean,
                                    'Price per Liter': np.mean,
                                    'Sale (Dollars)': {'TotalSales (Dollars)': sum, 
                                                       'AvgSaleRevenue': np.mean, 
                                                       'TotalTransactions': len}
                                    }
                            )
# Removed multi-index
sales2015.columns = [' '.join(col).strip() for col in sales2015.columns.values]
# Merged store_info dataframe and renamed columns
sales2015 = sales2015.merge(store_info, how='left', left_index=True, right_index=True)
sales2015.rename(columns={'Sale (Dollars) AvgSaleRevenue': 'Average Sale (Dollars)', 
                          'Sale (Dollars) TotalSales (Dollars)': 'Total Sales (Dollars)',
                          'Sale (Dollars) TotalTransactions': 'Total Transactions',
                          'State Bottle Retail mean': 'Average Price per Bottle (Dollars)',
                          'Price per Liter mean': 'Average Price per Liter (Dollars)',
                          'Bottles Sold sum': 'Total Bottles Sold',
                          'Volume Sold (Liters) Average Volume Sold': 'Average Volume per Sale (Liters)',
                          'Volume Sold (Liters) Total Volume Sold': 'Total Volume Sold (Liters)',
                          'Margin mean': 'Average Margin'}, inplace=True)
sales2015

,Average Sale (Dollars),Total Sales (Dollars),Total Transactions,Average Price per Bottle (Dollars),Average Price per Liter (Dollars),Total Bottles Sold,Average Volume per Sale (Liters),Total Volume Sold (Liters),Average Margin,City,County Number,Zip Code
Store Number,,,,,,,,,,,,
2106,277.658861,146326.22,527.0,15.475863,17.856601,10367,18.466509,9731.85,92.671879,CEDAR FALLS,7,50613
2113,63.334830,9310.22,147.0,16.315646,18.507700,671,4.488776,659.85,21.149932,GOWRIE,94,50543
2130,285.386301,111871.43,392.0,14.764286,16.835809,7430,17.580026,6891.37,95.217347,WATERLOO,7,50703
2178,102.633671,24324.18,237.0,14.558692,16.053844,1928,8.089114,1917.12,34.454430,WAUKON,3,52172
2190,92.539209,121689.06,1315.0,17.289726,23.306227,11111,4.807734,6322.17,30.888008,DES MOINES,77,50314
2191,209.888406,125093.49,596.0,17.327265,19.064053,7696,13.512282,8053.32,70.040923,KEOKUK,56,52632
2200,56.604342,22811.55,403.0,16.828337,16.706969,1668,4.509280,1817.24,18.991241,SAC CITY,81,50583
2228,72.758625,17462.07,240.0,14.613458,17.890101,1312,5.698542,1367.65,24.351417,WINTERSET,61,50273
2233,122.627967,29553.34,241.0,17.535021,19.945082,2253,10.293320,2480.69,40.940498,SPIRIT LAKE,30,51360
2248,147.134913,67682.06,460.0,22.581913,28.818620,3401,6.120326,2815.35,49.096761,DES MOINES,77,50312
2285,251.395784,76927.11,306.0,20.436307,24.776983,4552,12.615523,3860.35,84.055588,IOWA CITY,52,52240
2290,72.084732,56514.43,784.0,15.873584,19.001146,4053,4.625255,3626.20,24.084656,STORM LAKE,11,50588
2327,54.207090,10245.14,189.0,15.282063,17.324104,754,4.350688,822.28,18.082910,CORNING,2,50841
2413,187.245364,90065.02,481.0,15.040977,15.880172,6298,13.017235,6261.29,62.583825,DUBUQUE,31,52001
2445,42.043743,7189.48,171.0,14.832339,15.950097,574,3.343801,571.79,14.030351,OAKLAND,78,51560
2448,43.164720,17740.70,411.0,15.110414,17.035428,1257,3.030487,1245.53,14.414866,INDIANOLA,91,50125
2459,68.077130,7352.33,108.0,12.021574,13.574880,654,5.622593,607.24,22.769259,GUTHRIE CENTER,39,50115
2465,66.065985,25831.80,391.0,17.662072,20.776350,1934,4.381586,1713.20,22.071151,DUBUQUE,31,52003
2475,144.338784,10681.07,74.0,16.874459,15.482021,719,14.120811,1044.94,48.147568,WEST BEND,55,50597
2478,230.705233,19840.65,86.0,21.036744,24.755775,1110,12.069767,1038.00,76.923488,ALTOONA,77,50009
2498,38.959828,2259.67,58.0,9.258793,13.486032,251,3.967586,230.12,13.093448,ARLINGTON,33,50606
2500,126.481450,149121.63,1179.0,15.594996,18.988761,10676,8.514970,10039.15,42.240441,AMES,85,50010
2501,113.062966,144833.66,1281.0,14.963005,18.840306,10924,7.774707,9959.40,37.806971,AMES,85,50010
2502,195.180767,150094.01,769.0,16.847789,20.320363,10249,13.911691,10698.09,65.468544,ANKENY,77,50021
2505,117.625498,70810.55,602.0,13.581113,16.578905,5221,9.291445,5593.45,39.554850,BOONE,8,50036
2506,154.893801,143431.66,926.0,17.236685,20.593683,9472,9.743607,9022.58,51.755572,BURLINGTON,29,52601
2507,88.596358,29679.78,335.0,11.660149,14.131910,3031,7.588746,2542.23,29.578567,BURLINGTON,29,52601
2508,147.430318,115732.80,785.0,15.176306,18.249819,7880,10.016344,7862.83,49.249541,CEDAR RAPIDS,57,52405
2509,133.071551,49768.76,374.0,13.651684,15.703712,4091,10.165508,3801.90,44.515989,CEDAR RAPIDS,57,52404
2512,305.048568,419746.83,1376.0,16.401025,19.783300,27692,18.838576,25921.88,101.848445,IOWA CITY,52,52240
...,...,...,...,...,...,...,...,...,...,...,...,...
5017,68.310000,8060.58,118.0,12.360763,13.948283,732,6.346186,748.85,22.872966,LANSING,3,52151
5018,100.715722,19538.85,194.0,11.072680,21.028195,2672,6.194124,1201.66,33.594433,DAVENPORT,82,52802
5029,139.326713,30094.57,216.0,15.278657,22.872310,3078,7.421944,1603.14,46.495741,DAVENPORT,82,52806
5034,113.609489,19995.27,176.0,12.270852,17.226315,2592,7.379943,1298.87,37.923693,MASON CITY,17,50401
5037,57.020846,7412.71,130.0,18.381308,19.896397,457,3.685923,479.17,19.072615,JEFFERSON,37,50129
5039,134.554615,3498.42,26.0,12.492692,14.842454,294,11.019231,286.50,45.191538,SOLON,52,52333
5040,112.307368,2133.84,19.0,10.090000,16.238722,230,7.381053,140.24,37.455263,WILTON,70,52778
5042,117.964348,10852.72,92.0,12.129674,22.086781,1073,6.201630,570.55,39.343587,DUBUQUE,31,52001
5043,100.107793,14515.63,145.0,8.915103,17.191749,2413,6.949793,1007.72,33.425241,WATERLOO,7,50702
5045,104.771429,6600.60,63.0,11.382698,15.999902,1017,7.738095,487.50,34.944921,SIOUX CITY,97,51103
5048,78.317000,1566.34,20.0,14.284000,15.811714,112,6.462500,129.25,26.115000,ROLFE,76,50581
5050,195.363719,23639.01,121.0,14.000579,15.869189,1723,17.661157,2137.00,67.551901,CARLISLE,91,50047
5051,57.758454,5602.57,97.0,13.772784,22.869168,688,3.103505,301.04,19.265876,DES MOINES,77,50309
5052,121.594737,2310.30,19.0,10.375263,15.603659,294,8.992105,170.85,40.632632,GREENFIELD,1,50849
5054,129.176792,41078.22,318.0,15.357610,17.518206,3076,9.327044,2966.00,43.147107,MANCHESTER,28,52087
5057,73.422069,4258.48,58.0,12.556724,17.970691,397,4.732241,274.47,24.510690,DES MOINES,77,50317
5063,199.145242,24694.01,124.0,9.496532,20.123810,4579,11.073306,1373.09,66.408548,WATERLOO,7,50703
5064,109.793667,3293.81,30.0,9.721000,14.972381,358,8.475000,254.25,36.613333,FAIRFAX,57,52228
5065,37.894306,2728.39,72.0,11.040417,18.985144,347,2.398194,172.67,12.657083,SIOUX CITY,97,51106
5067,90.499785,8416.48,93.0,21.732151,29.319018,522,4.791505,445.61,30.272581,STORM LAKE,11,50588
5068,71.284653,21599.25,303.0,14.688878,17.685938,1605,4.918119,1490.19,23.778449,ARNOLDS PARK,30,51331
5070,29.476300,6691.12,227.0,11.608722,14.057682,634,2.798194,635.19,9.850044,WILTON,70,52778
5071,36.662513,7149.19,195.0,12.680513,14.812274,667,3.157795,615.77,12.255590,DURANT,16,52747
5072,127.473333,2676.94,21.0,12.634286,18.004717,248,10.285714,216.00,42.633333,MOUNT PLEASANT,44,52641
5073,172.317209,7409.64,43.0,13.171395,16.022746,660,11.574419,497.70,57.516279,CEDAR RAPIDS,57,52404
5077,160.067089,25290.60,158.0,14.678228,14.498002,1782,11.781646,1861.50,53.471392,COUNCIL BLUFFS,78,51501
5080,131.323631,23506.93,179.0,14.112570,16.424132,2318,12.928939,2314.28,43.828212,SPENCER,21,51301
5089,35.536000,3198.24,90.0,10.313333,18.981446,403,2.409111,216.82,11.850333,MISSOURI VALLEY,43,51555
5090,103.453784,3827.79,37.0,11.827297,19.725747,358,6.126757,226.69,34.609189,MUSCATINE,70,52761
5091,38.308519,2068.66,54.0,10.339630,18.522131,258,2.952222,159.42,12.852037,MUSCATINE,70,52761

**Sales by store for Q1 of 2015**

In [16]:
salesQ115 = pd.pivot_table(df[(df['Date'] >= pd.Timestamp("2015-01-01")) & (df['Date'] <= pd.Timestamp("2015-03-31"))], 
                           index='Store Number',
                           aggfunc={
                                    'Bottles Sold': sum,
                                    'State Bottle Retail': np.mean,
                                    'Volume Sold (Liters)': {'Total Volume Sold': sum, 'Average Volume Sold': np.mean},
                                    'Margin': np.mean,
                                    'Price per Liter': np.mean,
                                    'Sale (Dollars)': {'TotalSales (Dollars)': sum, 
                                                       'AvgSaleRevenue': np.mean, 
                                                       'TotalTransactions': len}
                                    }
                            )
salesQ115.columns = [' '.join(col).strip() for col in salesQ115.columns.values]
salesQ115 = salesQ115.merge(store_info, how='left', left_index=True, right_index=True)
salesQ115.rename(columns={'Sale (Dollars) AvgSaleRevenue': 'Average Sale (Dollars)', 
                          'Sale (Dollars) TotalSales (Dollars)': 'Total Sales (Dollars)',
                          'Sale (Dollars) TotalTransactions': 'Total Transactions',
                          'State Bottle Retail mean': 'Average Price per Bottle (Dollars)',
                          'Price per Liter mean': 'Average Price per Liter (Dollars)',
                          'Bottles Sold sum': 'Total Bottles Sold',
                          'Volume Sold (Liters) Average Volume Sold': 'Average Volume per Sale (Liters)',
                          'Volume Sold (Liters) Total Volume Sold': 'Total Volume Sold (Liters)',
                          'Margin mean': 'Average Margin'}, inplace=True)
salesQ115

,Average Sale (Dollars),Total Sales (Dollars),Total Transactions,Average Price per Bottle (Dollars),Average Price per Liter (Dollars),Total Bottles Sold,Average Volume per Sale (Liters),Total Volume Sold (Liters),Average Margin,City,County Number,Zip Code
Store Number,,,,,,,,,,,,
2106,304.552636,39287.29,129.0,15.075271,17.846608,2705,19.582171,2526.10,101.615271,CEDAR FALLS,7,50613
2113,67.458333,2833.25,42.0,15.821190,19.365167,196,4.216905,177.11,22.493333,GOWRIE,94,50543
2130,278.995057,24272.57,87.0,15.401379,17.565430,1533,16.635057,1447.25,93.203218,WATERLOO,7,50703
2178,122.008542,5856.41,48.0,14.748542,16.705494,490,8.537708,409.81,40.860000,WAUKON,3,52172
2190,84.878732,29452.92,347.0,16.376282,21.932514,2557,4.802824,1666.58,28.323631,DES MOINES,77,50314
2191,192.619669,29085.57,151.0,17.453974,18.591907,1868,12.962119,1957.28,64.393377,KEOKUK,56,52632
2200,58.338452,4900.43,84.0,17.595357,16.791219,338,4.377619,367.72,19.545238,SAC CITY,81,50583
2228,86.566167,5193.97,60.0,14.606833,17.102040,372,6.760333,405.62,28.940500,WINTERSET,61,50273
2233,124.989535,5374.55,43.0,17.556512,18.350133,368,9.763953,419.85,41.767674,SPIRIT LAKE,30,51360
2248,125.382970,12663.68,101.0,22.087327,26.738835,665,6.431089,649.54,41.853861,DES MOINES,77,50312
2285,172.743448,10019.12,58.0,24.401034,27.865468,522,8.680172,503.45,57.687931,IOWA CITY,52,52240
2290,76.195375,12191.26,160.0,16.360750,19.807089,870,5.109875,817.58,25.523250,STORM LAKE,11,50588
2327,52.409302,2253.60,43.0,14.982558,17.080401,174,4.262093,183.27,17.472326,CORNING,2,50841
2413,198.753628,22459.16,113.0,15.549823,16.194193,1511,13.613894,1538.37,66.380708,DUBUQUE,31,52001
2445,37.971250,1215.08,32.0,14.497813,15.546551,107,2.972188,95.11,12.677813,OAKLAND,78,51560
2448,50.499286,5655.92,112.0,15.405893,17.235158,361,3.259107,365.02,16.850536,INDIANOLA,91,50125
2459,73.162273,1609.57,22.0,12.335909,12.411515,133,6.227273,137.00,24.457727,GUTHRIE CENTER,39,50115
2465,57.306020,5615.99,98.0,17.711939,20.746404,452,4.082857,400.12,19.137857,DUBUQUE,31,52003
2475,283.638000,5672.76,20.0,18.016500,14.843012,394,32.707500,654.15,94.599500,WEST BEND,55,50597
2478,234.728947,4459.85,19.0,20.472632,22.788070,224,11.052632,210.00,78.257895,ALTOONA,77,50009
2498,27.922000,279.22,10.0,7.564000,14.111512,40,2.787000,27.87,9.313000,ARLINGTON,33,50606
2500,142.676950,40234.90,282.0,15.436879,18.330800,2950,11.208369,3160.76,47.643333,AMES,85,50010
2501,97.859657,31412.95,321.0,15.278972,18.861390,2321,6.755919,2168.65,32.718879,AMES,85,50010
2502,209.681170,39420.06,188.0,16.197660,19.107485,2692,16.675106,3134.92,71.075851,ANKENY,77,50021
2505,104.743022,14559.28,139.0,13.321007,16.254443,1112,7.399928,1028.59,35.060791,BOONE,8,50036
2506,152.008676,31009.77,204.0,16.399657,19.179434,2069,10.026569,2045.42,50.899461,BURLINGTON,29,52601
2507,88.766064,8344.01,94.0,11.627766,14.376199,823,7.324681,688.52,29.625000,BURLINGTON,29,52601
2508,143.657119,25427.31,177.0,14.918418,17.127272,2077,10.001921,1770.34,48.025028,CEDAR RAPIDS,57,52405
2509,150.880854,12372.23,82.0,13.952073,15.863859,953,10.915366,895.06,50.415488,CEDAR RAPIDS,57,52404
2512,228.105056,82117.82,360.0,16.576167,20.047370,5542,13.902167,5004.78,76.136361,IOWA CITY,52,52240
...,...,...,...,...,...,...,...,...,...,...,...,...
5017,66.168421,1257.20,19.0,10.714737,9.852462,124,8.348421,158.62,22.407895,LANSING,3,52151
5018,94.594528,5013.51,53.0,8.716981,19.516371,796,6.365849,337.39,31.555849,DAVENPORT,82,52802
5029,140.152500,6166.71,44.0,21.754545,30.497911,519,5.864773,258.05,46.757727,DAVENPORT,82,52806
5034,91.244419,3923.51,43.0,13.310698,19.288007,463,6.253488,268.90,30.483721,MASON CITY,17,50401
5037,67.462941,2293.74,34.0,16.667647,18.411831,148,4.099118,139.37,22.632941,JEFFERSON,37,50129
5039,188.145000,1505.16,8.0,11.308750,14.761667,132,16.125000,129.00,63.450000,SOLON,52,52333
5040,98.640000,591.84,6.0,11.111667,17.842341,53,6.436667,38.62,32.893333,WILTON,70,52778
5042,82.871818,1823.18,22.0,12.089545,17.456234,161,5.563636,122.40,27.639091,DUBUQUE,31,52001
5043,93.331176,3173.26,34.0,7.897353,14.913277,524,7.122059,242.15,31.126471,WATERLOO,7,50702
5045,80.209167,1925.02,24.0,11.944167,16.523472,336,6.814583,163.55,26.750833,SIOUX CITY,97,51103
5048,83.870000,335.48,4.0,12.310000,9.392381,28,11.250000,45.00,27.965000,ROLFE,76,50581
5050,293.680000,7048.32,24.0,14.362917,15.228968,493,30.781250,738.75,101.128333,CARLISLE,91,50047
5051,72.936923,1896.36,26.0,15.083846,22.576081,197,3.407692,88.60,24.326538,DES MOINES,77,50309
5052,84.882857,594.18,7.0,8.150000,13.869252,120,7.371429,51.60,28.542857,GREENFIELD,1,50849
5054,162.202462,10543.16,65.0,16.053692,18.008864,776,11.350769,737.80,54.132000,MANCHESTER,28,52087
5057,67.415455,741.57,11.0,10.390909,19.249697,78,3.777273,41.55,22.479091,DES MOINES,77,50317
5063,157.322414,4562.35,29.0,11.130690,21.761137,661,7.768966,225.30,52.455862,WATERLOO,7,50703
5064,68.565000,274.26,4.0,8.220000,10.960000,36,6.750000,27.00,22.875000,FAIRFAX,57,52228
5065,43.770000,787.86,18.0,12.796667,17.372963,115,2.761111,49.70,14.608333,SIOUX CITY,97,51106
5067,117.542222,1057.88,9.0,43.592222,45.876402,48,5.000000,45.00,39.630000,STORM LAKE,11,50588
5068,86.974000,5653.31,65.0,14.627538,15.625097,371,5.995692,389.72,29.002154,ARNOLDS PARK,30,51331
5070,32.276714,2259.37,70.0,10.488571,12.610636,213,3.095286,216.67,10.768000,WILTON,70,52778
5071,35.548864,1564.15,44.0,11.397955,13.971905,185,3.403409,149.75,11.857727,DURANT,16,52747
5072,131.240000,393.72,3.0,12.686667,16.915556,30,7.500000,22.50,43.760000,MOUNT PLEASANT,44,52641
5073,166.545000,1332.36,8.0,13.581250,14.947857,120,12.225000,97.80,55.537500,CEDAR RAPIDS,57,52404
5077,207.043448,6004.26,29.0,14.306207,16.109113,426,14.224138,412.50,69.312414,COUNCIL BLUFFS,78,51501
5080,120.404681,5659.02,47.0,14.123404,16.029686,584,8.878723,417.30,40.201915,SPENCER,21,51301
5089,26.788788,884.03,33.0,9.987879,20.301288,103,1.669697,55.10,8.931515,MISSOURI VALLEY,43,51555
5090,109.694500,2193.89,20.0,11.076500,19.583965,193,6.629500,132.59,36.776500,MUSCATINE,70,52761
5091,47.620000,523.82,11.0,11.541818,21.761653,42,3.352727,36.88,16.247273,MUSCATINE,70,52761

**Sales by store for Q1 of 2016**

In [17]:
salesQ116 = pd.pivot_table(df[(df['Date'] >= pd.Timestamp("2016-01-01")) & (df['Date'] <= pd.Timestamp("2016-03-31"))], 
                           index='Store Number',
                           aggfunc={
                                    'Bottles Sold': sum,
                                    'State Bottle Retail': np.mean,
                                    'Volume Sold (Liters)': {'Total Volume Sold': sum, 'Average Volume Sold': np.mean},
                                    'Margin': np.mean,
                                    'Price per Liter': np.mean,
                                    'Sale (Dollars)': {'TotalSales (Dollars)': sum, 
                                                       'AvgSaleRevenue': np.mean, 
                                                       'TotalTransactions': len}
                                    }
                            )
salesQ116.columns = [' '.join(col).strip() for col in salesQ116.columns.values]
salesQ116 = salesQ116.merge(store_info, how='left', left_index=True, right_index=True)
salesQ116.rename(columns={'Sale (Dollars) AvgSaleRevenue': 'Average Sale (Dollars)', 
                          'Sale (Dollars) TotalSales (Dollars)': 'Total Sales (Dollars)',
                          'Sale (Dollars) TotalTransactions': 'Total Transactions',
                          'State Bottle Retail mean': 'Average Price per Bottle (Dollars)',
                          'Price per Liter mean': 'Average Price per Liter (Dollars)',
                          'Bottles Sold sum': 'Total Bottles Sold',
                          'Volume Sold (Liters) Average Volume Sold': 'Average Volume per Sale (Liters)',
                          'Volume Sold (Liters) Total Volume Sold': 'Total Volume Sold (Liters)',
                          'Margin mean': 'Average Margin'}, inplace=True)
salesQ116

,Average Sale (Dollars),Total Sales (Dollars),Total Transactions,Average Price per Bottle (Dollars),Average Price per Liter (Dollars),Total Bottles Sold,Average Volume per Sale (Liters),Total Volume Sold (Liters),Average Margin,City,County Number,Zip Code
Store Number,,,,,,,,,,,,
2106,240.344488,30523.75,127.0,15.614567,18.064496,2220,16.675197,2117.75,80.233701,CEDAR FALLS,7,50613
2113,55.835135,2065.90,37.0,16.077297,17.483024,159,4.783784,177.00,18.742973,GOWRIE,94,50543
2130,238.086410,27856.11,117.0,15.932308,17.452157,1726,13.306838,1556.90,79.387094,WATERLOO,7,50703
2178,96.353448,5588.50,58.0,13.915345,15.101929,480,8.979310,520.80,32.220000,WAUKON,3,52172
2190,110.982926,34515.69,311.0,19.250836,26.651232,2567,4.879293,1517.46,37.007331,DES MOINES,77,50314
2191,331.036364,47338.20,143.0,17.015245,18.074705,2610,20.476364,2928.12,110.381329,KEOKUK,56,52632
2200,50.913049,4174.87,82.0,17.038780,17.534613,262,3.887561,318.78,16.975854,SAC CITY,81,50583
2228,46.763333,3086.38,66.0,15.306667,19.542326,229,3.164394,208.85,15.662727,WINTERSET,61,50273
2233,133.115306,6522.65,49.0,22.361020,24.754852,478,9.747347,477.62,44.402653,SPIRIT LAKE,30,51360
2248,145.241800,14524.18,100.0,22.615500,29.831242,714,5.627600,562.76,48.452100,DES MOINES,77,50312
2285,241.936346,12580.69,52.0,21.293654,25.588800,747,12.932692,672.50,80.665962,IOWA CITY,52,52240
2290,49.988054,12846.93,257.0,14.940428,18.861052,1007,3.380078,868.68,16.697665,STORM LAKE,11,50588
2327,48.812667,2196.57,45.0,15.132222,15.969329,201,3.535556,159.10,16.296000,CORNING,2,50841
2413,186.840240,23355.03,125.0,16.246640,17.216747,1584,12.888000,1611.00,62.379040,DUBUQUE,31,52001
2445,49.081724,1423.37,29.0,15.947241,15.959158,133,4.142069,120.12,16.367586,OAKLAND,78,51560
2448,71.682766,6738.18,94.0,15.370957,17.723910,428,4.398936,413.50,23.901170,INDIANOLA,91,50125
2459,72.987600,1824.69,25.0,14.721200,14.833695,115,5.670000,141.75,24.416800,GUTHRIE CENTER,39,50115
2465,76.910857,5383.76,70.0,21.332857,24.023513,370,4.983286,348.83,25.698286,DUBUQUE,31,52003
2475,149.689687,4790.07,32.0,17.538438,15.033237,308,14.788750,473.24,49.910000,WEST BEND,55,50597
2478,212.505714,4462.62,21.0,20.119048,23.461270,240,10.714286,225.00,70.865714,ALTOONA,77,50009
2498,43.352222,780.34,18.0,10.271667,13.382480,78,3.570556,64.27,14.456667,ARLINGTON,33,50606
2500,98.936228,33836.19,342.0,15.175906,19.069718,2407,6.329094,2164.55,33.008538,AMES,85,50010
2501,110.222574,29980.54,272.0,14.216985,18.135647,2345,7.698346,2093.95,36.789154,AMES,85,50010
2502,104.491044,19017.37,182.0,16.247253,18.085326,1329,7.075220,1287.69,34.855000,ANKENY,77,50021
2505,93.031401,14605.93,157.0,14.124586,17.067802,1137,7.075350,1110.83,31.088280,BOONE,8,50036
2506,133.231573,33041.43,248.0,15.135887,17.236031,2344,9.184597,2277.78,44.488710,BURLINGTON,29,52601
2507,105.999828,6147.99,58.0,12.051724,14.866232,650,8.655172,502.00,35.376034,BURLINGTON,29,52601
2508,168.508261,23254.14,138.0,16.104130,19.143350,1388,10.723841,1479.89,56.189493,CEDAR RAPIDS,57,52405
2509,104.837097,9749.85,93.0,14.061398,15.289149,877,8.754731,814.19,35.133978,CEDAR RAPIDS,57,52404
2512,294.551806,112518.79,382.0,16.521335,20.335049,7987,19.570838,7476.06,98.231047,IOWA CITY,52,52240
...,...,...,...,...,...,...,...,...,...,...,...,...
5017,73.213333,2416.04,33.0,13.144545,15.155902,226,6.568182,216.75,24.443939,LANSING,3,52151
5018,100.110968,6206.88,62.0,10.048548,23.285087,1033,5.779194,358.31,33.398387,DAVENPORT,82,52802
5029,118.837222,6417.21,54.0,15.163333,25.320032,588,6.050556,326.73,39.629074,DAVENPORT,82,52806
5034,97.295208,4670.17,48.0,11.516875,16.701677,560,6.875417,330.02,32.449792,MASON CITY,17,50401
5037,52.056857,1821.99,35.0,17.064857,16.075973,109,3.550000,124.25,17.358000,JEFFERSON,37,50129
5039,128.040000,896.28,7.0,10.661429,13.934558,96,10.114286,70.80,42.702857,SOLON,52,52333
5040,109.550000,657.30,6.0,14.913333,19.384127,60,7.000000,42.00,36.540000,WILTON,70,52778
5042,168.882105,3208.76,19.0,13.937368,31.547118,238,5.802632,110.25,56.312632,DUBUQUE,31,52001
5043,88.987273,2936.58,33.0,8.292424,16.384473,569,6.843939,225.85,29.685152,WATERLOO,7,50702
5045,92.661905,1945.90,21.0,12.533810,21.622857,289,6.438095,135.20,30.916190,SIOUX CITY,97,51103
5048,86.180000,1206.52,14.0,15.802143,15.405816,81,6.142857,86.00,28.735000,ROLFE,76,50581
5050,74.264737,2822.06,38.0,11.856053,14.947782,210,6.018421,228.70,24.786316,CARLISLE,91,50047
5051,56.264815,1519.15,27.0,12.736296,19.056520,163,3.668148,99.04,18.764074,DES MOINES,77,50309
5052,67.410000,404.46,6.0,7.748333,11.153016,64,7.125000,42.75,22.476667,GREENFIELD,1,50849
5054,143.244156,11029.80,77.0,15.476883,18.011132,829,11.298701,870.00,48.235584,MANCHESTER,28,52087
5057,61.700000,1295.70,21.0,11.732857,18.829721,104,3.960952,83.18,20.646190,DES MOINES,77,50317
5063,139.844615,3635.96,26.0,10.253077,19.909725,477,8.828846,229.55,46.652692,WATERLOO,7,50703
5064,117.640000,705.84,6.0,9.880000,14.924444,81,9.375000,56.25,39.230000,FAIRFAX,57,52228
5065,28.808500,576.17,20.0,9.572000,16.407142,107,2.311500,46.23,9.609500,SIOUX CITY,97,51106
5067,100.690000,2013.80,20.0,17.855500,21.519327,156,8.634500,172.69,34.336000,STORM LAKE,11,50588
5068,76.724483,4450.02,58.0,14.508276,15.817268,349,6.002931,348.17,25.583966,ARNOLDS PARK,30,51331
5070,32.254516,1999.78,62.0,12.058871,14.249243,196,2.928548,181.57,10.766129,WILTON,70,52778
5071,33.064615,1719.36,52.0,11.665962,14.247119,166,2.879808,149.75,11.024808,DURANT,16,52747
5072,144.414545,1588.56,11.0,12.926364,13.171948,132,12.272727,135.00,48.436364,MOUNT PLEASANT,44,52641
5073,165.130909,1816.44,11.0,12.878182,20.522208,215,9.245455,101.70,55.076364,CEDAR RAPIDS,57,52404
5077,151.647097,9402.12,62.0,14.389516,14.269647,648,11.709677,726.00,50.625484,COUNCIL BLUFFS,78,51501
5080,106.047407,5726.56,54.0,13.101296,14.106111,533,8.562037,462.35,35.490185,SPENCER,21,51301
5089,35.210800,880.27,25.0,10.718000,17.329124,164,3.032800,75.82,11.746400,MISSOURI VALLEY,43,51555
5090,69.884286,978.38,14.0,14.265714,15.718741,97,4.414286,61.80,23.308571,MUSCATINE,70,52761
5091,37.867727,833.09,22.0,11.228182,17.195328,100,2.880909,63.38,12.626818,MUSCATINE,70,52761

Proceed with any calculations that you need for your models, such as grouping
sales by zip code, most common vendor number per store, etc. Once you have finished adding columns, be sure to save the dataframe.

In [19]:
sales.to_csv("sales.csv")

KeyError: 'Date amin'